POST https://localhost:3000/update/
Content-Type: application/json

[{"productId":123,"quantity":10,"operation":"add"},

{"productId":143,"quantity":14,"operation":"add"},

{"productId":193,"quantity":17,"operation":"subtract"}]
